# NumPy Basics
Learning arrays and mathematical operations.

In [2]:
import numpy as np

In [3]:
numbers = np.array([10, 20, 30, 40, 50])
numbers

array([10, 20, 30, 40, 50])

In [4]:
numbers.shape

(5,)

In [5]:
numbers.dtype

dtype('int64')

In [11]:
python_list = [1, 2, 3]

numpy_array = np.array([1, 2, 3])

print(type(python_list))
print(type(numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers + 5)

[15 25 35 45 55]


In [13]:
print(numbers * 2)

[ 20  40  60  80 100]


In [14]:
print(numbers / 10)

[1. 2. 3. 4. 5.]


In [20]:
print(numbers[1:4])

[20 30 40]


In [15]:
print(numbers.mean())
print(numbers.sum())
print(numbers.max())
print(numbers.min())

30.0
150
50
10


In [16]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [17]:
print(matrix.shape)

(2, 3)


In [18]:
print(numbers[0])
print(numbers[-1])

10
50


In [19]:
print(matrix[0][1])

2


## Pandas + NumPy Quick Revision

### Series vs DataFrame
- Series → 1D labeled structure, usually one column
- DataFrame → 2D table with rows and columns

### DataFrame Shape

`df.shape` returns:

(rows, columns)

Example:

(1000, 8) → 1000 rows and 8 columns

### Vectorization

Pandas and NumPy can perform operations on entire columns/arrays
without manually writing Python loops.

Example:

df["Revenue"] = df["Price"] * df["Quantity"]

### Missing Values

df.isnull().sum()

→ Number of missing values in each column.

`dropna()` → removes missing observations (rows by default).

`fillna()` → replaces missing values.

Do not automatically drop or fill missing data.
The decision depends on the data and analytical problem.

### value_counts()

Counts the frequency of each unique value.

### NumPy

NumPy is used for efficient numerical computing.

Important:
- Fast numerical operations
- Vectorized operations
- Boolean filtering
- Multidimensional arrays

### Boolean Filtering

scores[scores >= 70]

Condition creates a Boolean mask and returns values
where the condition is True.

### Array Dimensions

A NumPy array is not automatically a matrix.

np.array([1, 2, 3]) → 1D

np.array([[1, 2], [3, 4]]) → 2D

Use:

arr.ndim

to check the number of dimensions.